# spring:
#  h2:
#    console:
#      enabled: true   # Habilita la consola (panel simil phpmyadmin)
#      path: /h2-console
#
#  jpa:
#    show-sql: true  # Habilita las querys JPA

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_veterinary
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    contextPath: /api   # Base path '/api' para toda la app